theme: jekyll-theme-minimal

title: Paul Stanish

logo: "51145028_10156442464583999_2637533845901017088_o.jpg?raw=true"

description:
  I have a PhD in chemistry and nanotechnology, I taught myself mobile development and data science, and I am looking for a job where I can make a difference.
  <br><br>
  (613) 883-7285
  <br><br>
  <a href="mailto:paul.stanish@gmail.com">paul.stanish@gmail.com</a>
  <br><br>
  <a href="www.linkedin.com/in/paulstanish">View My LinkedIn Profile</a>
  <br><br>
  <a href="https://hsinats.github.io/Paul Stanish - Resume.pdf">My Resume</a>
