theme: jekyll-theme-minimal

title: Paul Stanish

logo: "51145028_10156442464583999_2637533845901017088_o.jpg?raw=true"

description:
  <a href="www.linkedin.com/in/paulstanish">View My LinkedIn Profile</a>
  <br>
  <a href="https://github.com/Hsinats">View My GitHub Profile</a>
